### ISSUE TITLE
Fix hardcoded state problem on Ncdb_2010_blk_mac

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/NCDB#14]

**Comment by rpitingolo** [comment]
@ptatian hi Peter. It turns out this goes a lot deeper than I originally thought. In order to get the 2010 65+ variable for the whole region I need the MD/VA/WV equivalent of  this file: Census.Census_sf1_2010_dc_blks

It looks like the program that creates it is Census\Prog\2010\SF1\Census_sf1_2010_dc_blks.sas which sets a SAS dataset (dcblocks.sas7bdat) from the /raw/ folder. 

Where I get stuck is that I don't know where that dcblocks.sas7bdat dataset comes from. As far as I can tell there isn't a program that reads raw SF1 files in to create it. Any help here would be appreciated.

**Comment by ptatian** [comment]
Sorry about that, @rpitingolo. It appears that dcblocks file comes from here: http://mcdc.missouri.edu/data/sf12010/Datasets.html  

Looks like you can download the MD/VA/WV versions from the same place.

**Comment by rpitingolo** [comment]
@ptatian thanks. I just downloaded mdblocks and will test with that.

**Comment by rpitingolo** [comment]
@ptatian the query tool is extremely slow but seems to have worked.
