### ISSUE TITLE
Update Ncdb_sum_all.sas

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/NCDB#3]
@jdev42092 We should be able to fix this easily (I hope). We first need to update the NCDB\Prog\Ncdb_sum_all.sas program for the SAS1 system. 

- [x] Replace these lines with the new %include statement for SAS1
```
%include "K:\Metro\PTatian\DCData\SAS\Inc\Stdhead.sas";
%include "K:\Metro\PTatian\DCData\SAS\Inc\AlphaSignon.sas" /nosource2;
```

- [x] Delete the obsolete rsubmit;, endrsubmit;, and signoff; statements. 

- [x] Change the _revisions=_ parameter value to _%str(Add Bridge Park geo.)_

I've also made changes to the macros called by this program that we will need to deploy. I can do that later tonight or tomorrow morning. Let me know when you have done the changes to  the NCDB program.

**Comment by jdev42092** [comment]
@ptatian I've updated that program.
