### ISSUE TITLE
Add Pop65andOverYears variable to NCDB summary files. 

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/NCDB#5]

**Comment by rpitingolo** [comment]
@ptatian do you know where we have the documentation for the Census 2010 PL94-171 data? I need the ACS cell number from Census.Census_pl_2010_dc to create the 65+ variable.

**Comment by ptatian** [comment]
L:\Libraries\Census\Doc\ProgramDoc Census 2010 PL94-171.doc
