### ISSUE TITLE
Create NCDB data sets for entire Washington MSA

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/NCDB#9]
NCDB data for the MSA are needed for new Greater DC initiative web site. cc: @rpitingolo @lhendey

**Comment by ptatian** [comment]
Next steps:

- [x] Add code for 1990 NCDB summaries to Ncdb_sum_was15.sas
- [x] Write program for 2010 summary files

**Comment by ptatian** [comment]
@rpitingolo I've added **Ncdb.Ncdb_sum_was15_tr00** and **Ncdb.Ncdb_sum_was15_regcnt** data sets to L: with the NCDB 1990 and 2000 summary data for tracts and counties, respectively, in the Washington MSA. Please let me know if these seem compatible with the other data sets you are using for the new website. 

I'll be working on the 2010 data next.

cc: @lhendey

**Comment by ptatian** [comment]
@rpitingolo **Ncdb.Ncdb_sum_2010_was15_tr00** and **Ncdb.Ncdb_sum_2010_was15_regcnt**, with 2010 NCDB summary data, have now been added to L:. I'll leave the issue open until we confirm that these files are OK.

**Comment by rpitingolo** [comment]
@ptatian all of the NCDB files for the region have 2000 tracts (geo2000) but we need them in 2010 tracts (geo2010) for the new website. Did you ever figure out a way to make this happen? I can work on it if you know a way to do it. cc: @lhendey

**Comment by rpitingolo** [comment]
@ptatian disregard. I found the issue in the general repo. @lhendey

**Comment by rpitingolo** [comment]
@ptatian Ncdb.Ncdb_sum_was15_tr00 and Ncdb.Ncdb_sum_was15_regcnt are missing the foreign born and 65+ population variables.  I can go back and try to figure out how to add them, but since you created them originally I thought I'd ask if you know off-hand.

**Comment by ptatian** [comment]
@rpitingolo No, not offhand. They probably just need to be added to the Ncdb_sum_was15.sas program. Sorry about that.

**Comment by rpitingolo** [comment]
@ptatian ok. I just opened a new issue and will take a look at that program.

**Comment by rpitingolo** [comment]
@ptatian the query tool is extremely slow but seems to have worked.
